name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
      - run: cd backend && mvn test  # Fail early if tests break

  install:
    runs-on: ubuntu-latest
    needs: test  # Only runs if `test` succeeds
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
      - run: cd backend && mvn clean install -DskipTests
